// ignore_for_file: camel_case_types, non_constant_identifier_names
// Auto-generated by ffigen. Do not edit.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// FFI bindings for PSR Database C API
class PsrDatabaseBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  PsrDatabaseBindings(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  PsrDatabaseBindings.fromLookup(ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup)
      : _lookup = lookup;

  ffi.Pointer<ffi.Char> psr_error_string(
    int error,
  ) {
    return _psr_error_string(
      error,
    );
  }

  late final _psr_error_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int32)>>('psr_error_string');
  late final _psr_error_string = _psr_error_stringPtr.asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  ffi.Pointer<ffi.Char> psr_version() {
    return _psr_version();
  }

  late final _psr_versionPtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>('psr_version');
  late final _psr_version = _psr_versionPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  psr_database_options_t psr_database_options_default() {
    return _psr_database_options_default();
  }

  late final _psr_database_options_defaultPtr =
      _lookup<ffi.NativeFunction<psr_database_options_t Function()>>('psr_database_options_default');
  late final _psr_database_options_default =
      _psr_database_options_defaultPtr.asFunction<psr_database_options_t Function()>();

  ffi.Pointer<psr_database_t> psr_database_open(
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<psr_database_options_t> options,
  ) {
    return _psr_database_open(
      path,
      options,
    );
  }

  late final _psr_database_openPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<psr_database_t> Function(
              ffi.Pointer<ffi.Char>, ffi.Pointer<psr_database_options_t>)>>('psr_database_open');
  late final _psr_database_open = _psr_database_openPtr
      .asFunction<ffi.Pointer<psr_database_t> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<psr_database_options_t>)>();

  ffi.Pointer<psr_database_t> psr_database_from_migrations(
    ffi.Pointer<ffi.Char> db_path,
    ffi.Pointer<ffi.Char> migrations_path,
    ffi.Pointer<psr_database_options_t> options,
  ) {
    return _psr_database_from_migrations(
      db_path,
      migrations_path,
      options,
    );
  }

  late final _psr_database_from_migrationsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<psr_database_t> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<psr_database_options_t>)>>('psr_database_from_migrations');
  late final _psr_database_from_migrations = _psr_database_from_migrationsPtr.asFunction<
      ffi.Pointer<psr_database_t> Function(
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<psr_database_options_t>)>();

  ffi.Pointer<psr_database_t> psr_database_from_schema(
    ffi.Pointer<ffi.Char> db_path,
    ffi.Pointer<ffi.Char> schema_path,
    ffi.Pointer<psr_database_options_t> options,
  ) {
    return _psr_database_from_schema(
      db_path,
      schema_path,
      options,
    );
  }

  late final _psr_database_from_schemaPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<psr_database_t> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<psr_database_options_t>)>>('psr_database_from_schema');
  late final _psr_database_from_schema = _psr_database_from_schemaPtr.asFunction<
      ffi.Pointer<psr_database_t> Function(
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<psr_database_options_t>)>();

  void psr_database_close(
    ffi.Pointer<psr_database_t> db,
  ) {
    return _psr_database_close(
      db,
    );
  }

  late final _psr_database_closePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<psr_database_t>)>>('psr_database_close');
  late final _psr_database_close = _psr_database_closePtr.asFunction<void Function(ffi.Pointer<psr_database_t>)>();

  int psr_database_is_healthy(
    ffi.Pointer<psr_database_t> db,
  ) {
    return _psr_database_is_healthy(
      db,
    );
  }

  late final _psr_database_is_healthyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<psr_database_t>)>>('psr_database_is_healthy');
  late final _psr_database_is_healthy =
      _psr_database_is_healthyPtr.asFunction<int Function(ffi.Pointer<psr_database_t>)>();

  ffi.Pointer<ffi.Char> psr_database_path(
    ffi.Pointer<psr_database_t> db,
  ) {
    return _psr_database_path(
      db,
    );
  }

  late final _psr_database_pathPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<psr_database_t>)>>('psr_database_path');
  late final _psr_database_path =
      _psr_database_pathPtr.asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<psr_database_t>)>();

  int psr_database_current_version(
    ffi.Pointer<psr_database_t> db,
  ) {
    return _psr_database_current_version(
      db,
    );
  }

  late final _psr_database_current_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<psr_database_t>)>>('psr_database_current_version');
  late final _psr_database_current_version =
      _psr_database_current_versionPtr.asFunction<int Function(ffi.Pointer<psr_database_t>)>();

  int psr_database_create_element(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<psr_element_t> element,
  ) {
    return _psr_database_create_element(
      db,
      collection,
      element,
    );
  }

  late final _psr_database_create_elementPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<psr_element_t>)>>('psr_database_create_element');
  late final _psr_database_create_element = _psr_database_create_elementPtr
      .asFunction<int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<psr_element_t>)>();

  int psr_database_update_element(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    int id,
    ffi.Pointer<psr_element_t> element,
  ) {
    return _psr_database_update_element(
      db,
      collection,
      id,
      element,
    );
  }

  late final _psr_database_update_elementPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Int64,
              ffi.Pointer<psr_element_t>)>>('psr_database_update_element');
  late final _psr_database_update_element = _psr_database_update_elementPtr
      .asFunction<int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, int, ffi.Pointer<psr_element_t>)>();

  int psr_database_delete_element_by_id(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    int id,
  ) {
    return _psr_database_delete_element_by_id(
      db,
      collection,
      id,
    );
  }

  late final _psr_database_delete_element_by_idPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Int64)>>(
          'psr_database_delete_element_by_id');
  late final _psr_database_delete_element_by_id = _psr_database_delete_element_by_idPtr
      .asFunction<int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, int)>();

  int psr_database_set_scalar_relation(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    ffi.Pointer<ffi.Char> from_label,
    ffi.Pointer<ffi.Char> to_label,
  ) {
    return _psr_database_set_scalar_relation(
      db,
      collection,
      attribute,
      from_label,
      to_label,
    );
  }

  late final _psr_database_set_scalar_relationPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('psr_database_set_scalar_relation');
  late final _psr_database_set_scalar_relation = _psr_database_set_scalar_relationPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  int psr_database_read_scalar_relation(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>> out_values,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_scalar_relation(
      db,
      collection,
      attribute,
      out_values,
      out_count,
    );
  }

  late final _psr_database_read_scalar_relationPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<psr_database_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>,
              ffi.Pointer<ffi.Size>)>>('psr_database_read_scalar_relation');
  late final _psr_database_read_scalar_relation = _psr_database_read_scalar_relationPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>, ffi.Pointer<ffi.Size>)>();

  int psr_database_read_scalar_integers(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    ffi.Pointer<ffi.Pointer<ffi.Int64>> out_values,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_scalar_integers(
      db,
      collection,
      attribute,
      out_values,
      out_count,
    );
  }

  late final _psr_database_read_scalar_integersPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Int64>>, ffi.Pointer<ffi.Size>)>>('psr_database_read_scalar_integers');
  late final _psr_database_read_scalar_integers = _psr_database_read_scalar_integersPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Int64>>, ffi.Pointer<ffi.Size>)>();

  int psr_database_read_scalar_floats(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    ffi.Pointer<ffi.Pointer<ffi.Double>> out_values,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_scalar_floats(
      db,
      collection,
      attribute,
      out_values,
      out_count,
    );
  }

  late final _psr_database_read_scalar_floatsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Double>>, ffi.Pointer<ffi.Size>)>>('psr_database_read_scalar_floats');
  late final _psr_database_read_scalar_floats = _psr_database_read_scalar_floatsPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Double>>, ffi.Pointer<ffi.Size>)>();

  int psr_database_read_scalar_strings(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>> out_values,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_scalar_strings(
      db,
      collection,
      attribute,
      out_values,
      out_count,
    );
  }

  late final _psr_database_read_scalar_stringsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<psr_database_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>,
              ffi.Pointer<ffi.Size>)>>('psr_database_read_scalar_strings');
  late final _psr_database_read_scalar_strings = _psr_database_read_scalar_stringsPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>, ffi.Pointer<ffi.Size>)>();

  int psr_database_read_vector_integers(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Int64>>> out_vectors,
    ffi.Pointer<ffi.Pointer<ffi.Size>> out_sizes,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_vector_integers(
      db,
      collection,
      attribute,
      out_vectors,
      out_sizes,
      out_count,
    );
  }

  late final _psr_database_read_vector_integersPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<psr_database_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Int64>>>,
              ffi.Pointer<ffi.Pointer<ffi.Size>>,
              ffi.Pointer<ffi.Size>)>>('psr_database_read_vector_integers');
  late final _psr_database_read_vector_integers = _psr_database_read_vector_integersPtr.asFunction<
      int Function(
          ffi.Pointer<psr_database_t>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Int64>>>,
          ffi.Pointer<ffi.Pointer<ffi.Size>>,
          ffi.Pointer<ffi.Size>)>();

  int psr_database_read_vector_floats(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Double>>> out_vectors,
    ffi.Pointer<ffi.Pointer<ffi.Size>> out_sizes,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_vector_floats(
      db,
      collection,
      attribute,
      out_vectors,
      out_sizes,
      out_count,
    );
  }

  late final _psr_database_read_vector_floatsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<psr_database_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Double>>>,
              ffi.Pointer<ffi.Pointer<ffi.Size>>,
              ffi.Pointer<ffi.Size>)>>('psr_database_read_vector_floats');
  late final _psr_database_read_vector_floats = _psr_database_read_vector_floatsPtr.asFunction<
      int Function(
          ffi.Pointer<psr_database_t>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Double>>>,
          ffi.Pointer<ffi.Pointer<ffi.Size>>,
          ffi.Pointer<ffi.Size>)>();

  int psr_database_read_vector_strings(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>> out_vectors,
    ffi.Pointer<ffi.Pointer<ffi.Size>> out_sizes,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_vector_strings(
      db,
      collection,
      attribute,
      out_vectors,
      out_sizes,
      out_count,
    );
  }

  late final _psr_database_read_vector_stringsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<psr_database_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>>,
              ffi.Pointer<ffi.Pointer<ffi.Size>>,
              ffi.Pointer<ffi.Size>)>>('psr_database_read_vector_strings');
  late final _psr_database_read_vector_strings = _psr_database_read_vector_stringsPtr.asFunction<
      int Function(
          ffi.Pointer<psr_database_t>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>>,
          ffi.Pointer<ffi.Pointer<ffi.Size>>,
          ffi.Pointer<ffi.Size>)>();

  int psr_database_read_set_integers(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Int64>>> out_sets,
    ffi.Pointer<ffi.Pointer<ffi.Size>> out_sizes,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_set_integers(
      db,
      collection,
      attribute,
      out_sets,
      out_sizes,
      out_count,
    );
  }

  late final _psr_database_read_set_integersPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<psr_database_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Int64>>>,
              ffi.Pointer<ffi.Pointer<ffi.Size>>,
              ffi.Pointer<ffi.Size>)>>('psr_database_read_set_integers');
  late final _psr_database_read_set_integers = _psr_database_read_set_integersPtr.asFunction<
      int Function(
          ffi.Pointer<psr_database_t>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Int64>>>,
          ffi.Pointer<ffi.Pointer<ffi.Size>>,
          ffi.Pointer<ffi.Size>)>();

  int psr_database_read_set_floats(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Double>>> out_sets,
    ffi.Pointer<ffi.Pointer<ffi.Size>> out_sizes,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_set_floats(
      db,
      collection,
      attribute,
      out_sets,
      out_sizes,
      out_count,
    );
  }

  late final _psr_database_read_set_floatsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<psr_database_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Double>>>,
              ffi.Pointer<ffi.Pointer<ffi.Size>>,
              ffi.Pointer<ffi.Size>)>>('psr_database_read_set_floats');
  late final _psr_database_read_set_floats = _psr_database_read_set_floatsPtr.asFunction<
      int Function(
          ffi.Pointer<psr_database_t>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Double>>>,
          ffi.Pointer<ffi.Pointer<ffi.Size>>,
          ffi.Pointer<ffi.Size>)>();

  int psr_database_read_set_strings(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>> out_sets,
    ffi.Pointer<ffi.Pointer<ffi.Size>> out_sizes,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_set_strings(
      db,
      collection,
      attribute,
      out_sets,
      out_sizes,
      out_count,
    );
  }

  late final _psr_database_read_set_stringsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<psr_database_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>>,
              ffi.Pointer<ffi.Pointer<ffi.Size>>,
              ffi.Pointer<ffi.Size>)>>('psr_database_read_set_strings');
  late final _psr_database_read_set_strings = _psr_database_read_set_stringsPtr.asFunction<
      int Function(
          ffi.Pointer<psr_database_t>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>>,
          ffi.Pointer<ffi.Pointer<ffi.Size>>,
          ffi.Pointer<ffi.Size>)>();

  int psr_database_read_scalar_integers_by_id(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    ffi.Pointer<ffi.Int64> out_value,
    ffi.Pointer<ffi.Int> out_has_value,
  ) {
    return _psr_database_read_scalar_integers_by_id(
      db,
      collection,
      attribute,
      id,
      out_value,
      out_has_value,
    );
  }

  late final _psr_database_read_scalar_integers_by_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int64,
              ffi.Pointer<ffi.Int64>, ffi.Pointer<ffi.Int>)>>('psr_database_read_scalar_integers_by_id');
  late final _psr_database_read_scalar_integers_by_id = _psr_database_read_scalar_integers_by_idPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Int64>, ffi.Pointer<ffi.Int>)>();

  int psr_database_read_scalar_floats_by_id(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    ffi.Pointer<ffi.Double> out_value,
    ffi.Pointer<ffi.Int> out_has_value,
  ) {
    return _psr_database_read_scalar_floats_by_id(
      db,
      collection,
      attribute,
      id,
      out_value,
      out_has_value,
    );
  }

  late final _psr_database_read_scalar_floats_by_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int64,
              ffi.Pointer<ffi.Double>, ffi.Pointer<ffi.Int>)>>('psr_database_read_scalar_floats_by_id');
  late final _psr_database_read_scalar_floats_by_id = _psr_database_read_scalar_floats_by_idPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Double>, ffi.Pointer<ffi.Int>)>();

  int psr_database_read_scalar_strings_by_id(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_value,
    ffi.Pointer<ffi.Int> out_has_value,
  ) {
    return _psr_database_read_scalar_strings_by_id(
      db,
      collection,
      attribute,
      id,
      out_value,
      out_has_value,
    );
  }

  late final _psr_database_read_scalar_strings_by_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int64,
              ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Int>)>>('psr_database_read_scalar_strings_by_id');
  late final _psr_database_read_scalar_strings_by_id = _psr_database_read_scalar_strings_by_idPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Int>)>();

  int psr_database_read_vector_integers_by_id(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    ffi.Pointer<ffi.Pointer<ffi.Int64>> out_values,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_vector_integers_by_id(
      db,
      collection,
      attribute,
      id,
      out_values,
      out_count,
    );
  }

  late final _psr_database_read_vector_integers_by_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int64,
              ffi.Pointer<ffi.Pointer<ffi.Int64>>, ffi.Pointer<ffi.Size>)>>('psr_database_read_vector_integers_by_id');
  late final _psr_database_read_vector_integers_by_id = _psr_database_read_vector_integers_by_idPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Pointer<ffi.Int64>>, ffi.Pointer<ffi.Size>)>();

  int psr_database_read_vector_floats_by_id(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    ffi.Pointer<ffi.Pointer<ffi.Double>> out_values,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_vector_floats_by_id(
      db,
      collection,
      attribute,
      id,
      out_values,
      out_count,
    );
  }

  late final _psr_database_read_vector_floats_by_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int64,
              ffi.Pointer<ffi.Pointer<ffi.Double>>, ffi.Pointer<ffi.Size>)>>('psr_database_read_vector_floats_by_id');
  late final _psr_database_read_vector_floats_by_id = _psr_database_read_vector_floats_by_idPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Pointer<ffi.Double>>, ffi.Pointer<ffi.Size>)>();

  int psr_database_read_vector_strings_by_id(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>> out_values,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_vector_strings_by_id(
      db,
      collection,
      attribute,
      id,
      out_values,
      out_count,
    );
  }

  late final _psr_database_read_vector_strings_by_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<psr_database_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int64,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>,
              ffi.Pointer<ffi.Size>)>>('psr_database_read_vector_strings_by_id');
  late final _psr_database_read_vector_strings_by_id = _psr_database_read_vector_strings_by_idPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>, ffi.Pointer<ffi.Size>)>();

  int psr_database_read_set_integers_by_id(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    ffi.Pointer<ffi.Pointer<ffi.Int64>> out_values,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_set_integers_by_id(
      db,
      collection,
      attribute,
      id,
      out_values,
      out_count,
    );
  }

  late final _psr_database_read_set_integers_by_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int64,
              ffi.Pointer<ffi.Pointer<ffi.Int64>>, ffi.Pointer<ffi.Size>)>>('psr_database_read_set_integers_by_id');
  late final _psr_database_read_set_integers_by_id = _psr_database_read_set_integers_by_idPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Pointer<ffi.Int64>>, ffi.Pointer<ffi.Size>)>();

  int psr_database_read_set_floats_by_id(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    ffi.Pointer<ffi.Pointer<ffi.Double>> out_values,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_set_floats_by_id(
      db,
      collection,
      attribute,
      id,
      out_values,
      out_count,
    );
  }

  late final _psr_database_read_set_floats_by_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int64,
              ffi.Pointer<ffi.Pointer<ffi.Double>>, ffi.Pointer<ffi.Size>)>>('psr_database_read_set_floats_by_id');
  late final _psr_database_read_set_floats_by_id = _psr_database_read_set_floats_by_idPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Pointer<ffi.Double>>, ffi.Pointer<ffi.Size>)>();

  int psr_database_read_set_strings_by_id(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>> out_values,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_set_strings_by_id(
      db,
      collection,
      attribute,
      id,
      out_values,
      out_count,
    );
  }

  late final _psr_database_read_set_strings_by_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<psr_database_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int64,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>,
              ffi.Pointer<ffi.Size>)>>('psr_database_read_set_strings_by_id');
  late final _psr_database_read_set_strings_by_id = _psr_database_read_set_strings_by_idPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>, ffi.Pointer<ffi.Size>)>();

  int psr_database_read_element_ids(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Pointer<ffi.Int64>> out_ids,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_element_ids(
      db,
      collection,
      out_ids,
      out_count,
    );
  }

  late final _psr_database_read_element_idsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Int64>>,
              ffi.Pointer<ffi.Size>)>>('psr_database_read_element_ids');
  late final _psr_database_read_element_ids = _psr_database_read_element_idsPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Int64>>,
          ffi.Pointer<ffi.Size>)>();

  int psr_database_get_attribute_type(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    ffi.Pointer<ffi.Int32> out_data_structure,
    ffi.Pointer<ffi.Int32> out_data_type,
  ) {
    return _psr_database_get_attribute_type(
      db,
      collection,
      attribute,
      out_data_structure,
      out_data_type,
    );
  }

  late final _psr_database_get_attribute_typePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Int32>, ffi.Pointer<ffi.Int32>)>>('psr_database_get_attribute_type');
  late final _psr_database_get_attribute_type = _psr_database_get_attribute_typePtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int32>,
          ffi.Pointer<ffi.Int32>)>();

  int psr_database_update_scalar_integer(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    int value,
  ) {
    return _psr_database_update_scalar_integer(
      db,
      collection,
      attribute,
      id,
      value,
    );
  }

  late final _psr_database_update_scalar_integerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int64,
              ffi.Int64)>>('psr_database_update_scalar_integer');
  late final _psr_database_update_scalar_integer = _psr_database_update_scalar_integerPtr
      .asFunction<int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int, int)>();

  int psr_database_update_scalar_float(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    double value,
  ) {
    return _psr_database_update_scalar_float(
      db,
      collection,
      attribute,
      id,
      value,
    );
  }

  late final _psr_database_update_scalar_floatPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int64,
              ffi.Double)>>('psr_database_update_scalar_float');
  late final _psr_database_update_scalar_float = _psr_database_update_scalar_floatPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int, double)>();

  int psr_database_update_scalar_string(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _psr_database_update_scalar_string(
      db,
      collection,
      attribute,
      id,
      value,
    );
  }

  late final _psr_database_update_scalar_stringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int64,
              ffi.Pointer<ffi.Char>)>>('psr_database_update_scalar_string');
  late final _psr_database_update_scalar_string = _psr_database_update_scalar_stringPtr.asFunction<
      int Function(
          ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Char>)>();

  int psr_database_update_vector_integers(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    ffi.Pointer<ffi.Int64> values,
    int count,
  ) {
    return _psr_database_update_vector_integers(
      db,
      collection,
      attribute,
      id,
      values,
      count,
    );
  }

  late final _psr_database_update_vector_integersPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int64,
              ffi.Pointer<ffi.Int64>, ffi.Size)>>('psr_database_update_vector_integers');
  late final _psr_database_update_vector_integers = _psr_database_update_vector_integersPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Int64>, int)>();

  int psr_database_update_vector_floats(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    ffi.Pointer<ffi.Double> values,
    int count,
  ) {
    return _psr_database_update_vector_floats(
      db,
      collection,
      attribute,
      id,
      values,
      count,
    );
  }

  late final _psr_database_update_vector_floatsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int64,
              ffi.Pointer<ffi.Double>, ffi.Size)>>('psr_database_update_vector_floats');
  late final _psr_database_update_vector_floats = _psr_database_update_vector_floatsPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Double>, int)>();

  int psr_database_update_vector_strings(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    ffi.Pointer<ffi.Pointer<ffi.Char>> values,
    int count,
  ) {
    return _psr_database_update_vector_strings(
      db,
      collection,
      attribute,
      id,
      values,
      count,
    );
  }

  late final _psr_database_update_vector_stringsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int64,
              ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Size)>>('psr_database_update_vector_strings');
  late final _psr_database_update_vector_strings = _psr_database_update_vector_stringsPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>, int)>();

  int psr_database_update_set_integers(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    ffi.Pointer<ffi.Int64> values,
    int count,
  ) {
    return _psr_database_update_set_integers(
      db,
      collection,
      attribute,
      id,
      values,
      count,
    );
  }

  late final _psr_database_update_set_integersPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int64,
              ffi.Pointer<ffi.Int64>, ffi.Size)>>('psr_database_update_set_integers');
  late final _psr_database_update_set_integers = _psr_database_update_set_integersPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Int64>, int)>();

  int psr_database_update_set_floats(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    ffi.Pointer<ffi.Double> values,
    int count,
  ) {
    return _psr_database_update_set_floats(
      db,
      collection,
      attribute,
      id,
      values,
      count,
    );
  }

  late final _psr_database_update_set_floatsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int64,
              ffi.Pointer<ffi.Double>, ffi.Size)>>('psr_database_update_set_floats');
  late final _psr_database_update_set_floats = _psr_database_update_set_floatsPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Double>, int)>();

  int psr_database_update_set_strings(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    int id,
    ffi.Pointer<ffi.Pointer<ffi.Char>> values,
    int count,
  ) {
    return _psr_database_update_set_strings(
      db,
      collection,
      attribute,
      id,
      values,
      count,
    );
  }

  late final _psr_database_update_set_stringsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int64,
              ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Size)>>('psr_database_update_set_strings');
  late final _psr_database_update_set_strings = _psr_database_update_set_stringsPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>, int)>();

  void psr_free_integer_array(
    ffi.Pointer<ffi.Int64> values,
  ) {
    return _psr_free_integer_array(
      values,
    );
  }

  late final _psr_free_integer_arrayPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Int64>)>>('psr_free_integer_array');
  late final _psr_free_integer_array = _psr_free_integer_arrayPtr.asFunction<void Function(ffi.Pointer<ffi.Int64>)>();

  void psr_free_float_array(
    ffi.Pointer<ffi.Double> values,
  ) {
    return _psr_free_float_array(
      values,
    );
  }

  late final _psr_free_float_arrayPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Double>)>>('psr_free_float_array');
  late final _psr_free_float_array = _psr_free_float_arrayPtr.asFunction<void Function(ffi.Pointer<ffi.Double>)>();

  void psr_free_string_array(
    ffi.Pointer<ffi.Pointer<ffi.Char>> values,
    int count,
  ) {
    return _psr_free_string_array(
      values,
      count,
    );
  }

  late final _psr_free_string_arrayPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Size)>>(
          'psr_free_string_array');
  late final _psr_free_string_array =
      _psr_free_string_arrayPtr.asFunction<void Function(ffi.Pointer<ffi.Pointer<ffi.Char>>, int)>();

  void psr_free_integer_vectors(
    ffi.Pointer<ffi.Pointer<ffi.Int64>> vectors,
    ffi.Pointer<ffi.Size> sizes,
    int count,
  ) {
    return _psr_free_integer_vectors(
      vectors,
      sizes,
      count,
    );
  }

  late final _psr_free_integer_vectorsPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Pointer<ffi.Int64>>, ffi.Pointer<ffi.Size>, ffi.Size)>>(
      'psr_free_integer_vectors');
  late final _psr_free_integer_vectors = _psr_free_integer_vectorsPtr
      .asFunction<void Function(ffi.Pointer<ffi.Pointer<ffi.Int64>>, ffi.Pointer<ffi.Size>, int)>();

  void psr_free_float_vectors(
    ffi.Pointer<ffi.Pointer<ffi.Double>> vectors,
    ffi.Pointer<ffi.Size> sizes,
    int count,
  ) {
    return _psr_free_float_vectors(
      vectors,
      sizes,
      count,
    );
  }

  late final _psr_free_float_vectorsPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Pointer<ffi.Double>>, ffi.Pointer<ffi.Size>, ffi.Size)>>(
      'psr_free_float_vectors');
  late final _psr_free_float_vectors = _psr_free_float_vectorsPtr
      .asFunction<void Function(ffi.Pointer<ffi.Pointer<ffi.Double>>, ffi.Pointer<ffi.Size>, int)>();

  void psr_free_string_vectors(
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>> vectors,
    ffi.Pointer<ffi.Size> sizes,
    int count,
  ) {
    return _psr_free_string_vectors(
      vectors,
      sizes,
      count,
    );
  }

  late final _psr_free_string_vectorsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>, ffi.Pointer<ffi.Size>,
              ffi.Size)>>('psr_free_string_vectors');
  late final _psr_free_string_vectors = _psr_free_string_vectorsPtr
      .asFunction<void Function(ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>, ffi.Pointer<ffi.Size>, int)>();

  ffi.Pointer<psr_element_t1> psr_element_create() {
    return _psr_element_create();
  }

  late final _psr_element_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<psr_element_t1> Function()>>('psr_element_create');
  late final _psr_element_create = _psr_element_createPtr.asFunction<ffi.Pointer<psr_element_t1> Function()>();

  void psr_element_destroy(
    ffi.Pointer<psr_element_t1> element,
  ) {
    return _psr_element_destroy(
      element,
    );
  }

  late final _psr_element_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<psr_element_t1>)>>('psr_element_destroy');
  late final _psr_element_destroy = _psr_element_destroyPtr.asFunction<void Function(ffi.Pointer<psr_element_t1>)>();

  void psr_element_clear(
    ffi.Pointer<psr_element_t1> element,
  ) {
    return _psr_element_clear(
      element,
    );
  }

  late final _psr_element_clearPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<psr_element_t1>)>>('psr_element_clear');
  late final _psr_element_clear = _psr_element_clearPtr.asFunction<void Function(ffi.Pointer<psr_element_t1>)>();

  int psr_element_set_integer(
    ffi.Pointer<psr_element_t1> element,
    ffi.Pointer<ffi.Char> name,
    int value,
  ) {
    return _psr_element_set_integer(
      element,
      name,
      value,
    );
  }

  late final _psr_element_set_integerPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>, ffi.Int64)>>(
          'psr_element_set_integer');
  late final _psr_element_set_integer =
      _psr_element_set_integerPtr.asFunction<int Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>, int)>();

  int psr_element_set_float(
    ffi.Pointer<psr_element_t1> element,
    ffi.Pointer<ffi.Char> name,
    double value,
  ) {
    return _psr_element_set_float(
      element,
      name,
      value,
    );
  }

  late final _psr_element_set_floatPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>, ffi.Double)>>(
          'psr_element_set_float');
  late final _psr_element_set_float =
      _psr_element_set_floatPtr.asFunction<int Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>, double)>();

  int psr_element_set_string(
    ffi.Pointer<psr_element_t1> element,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _psr_element_set_string(
      element,
      name,
      value,
    );
  }

  late final _psr_element_set_stringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('psr_element_set_string');
  late final _psr_element_set_string = _psr_element_set_stringPtr
      .asFunction<int Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  int psr_element_set_null(
    ffi.Pointer<psr_element_t1> element,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _psr_element_set_null(
      element,
      name,
    );
  }

  late final _psr_element_set_nullPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>)>>(
          'psr_element_set_null');
  late final _psr_element_set_null =
      _psr_element_set_nullPtr.asFunction<int Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>)>();

  int psr_element_set_array_integer(
    ffi.Pointer<psr_element_t1> element,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Int64> values,
    int count,
  ) {
    return _psr_element_set_array_integer(
      element,
      name,
      values,
      count,
    );
  }

  late final _psr_element_set_array_integerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int64>,
              ffi.Int32)>>('psr_element_set_array_integer');
  late final _psr_element_set_array_integer = _psr_element_set_array_integerPtr
      .asFunction<int Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int64>, int)>();

  int psr_element_set_array_float(
    ffi.Pointer<psr_element_t1> element,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Double> values,
    int count,
  ) {
    return _psr_element_set_array_float(
      element,
      name,
      values,
      count,
    );
  }

  late final _psr_element_set_array_floatPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Double>,
              ffi.Int32)>>('psr_element_set_array_float');
  late final _psr_element_set_array_float = _psr_element_set_array_floatPtr
      .asFunction<int Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Double>, int)>();

  int psr_element_set_array_string(
    ffi.Pointer<psr_element_t1> element,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Pointer<ffi.Char>> values,
    int count,
  ) {
    return _psr_element_set_array_string(
      element,
      name,
      values,
      count,
    );
  }

  late final _psr_element_set_array_stringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Int32)>>('psr_element_set_array_string');
  late final _psr_element_set_array_string = _psr_element_set_array_stringPtr.asFunction<
      int Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>, int)>();

  int psr_element_has_scalars(
    ffi.Pointer<psr_element_t1> element,
  ) {
    return _psr_element_has_scalars(
      element,
    );
  }

  late final _psr_element_has_scalarsPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<psr_element_t1>)>>('psr_element_has_scalars');
  late final _psr_element_has_scalars =
      _psr_element_has_scalarsPtr.asFunction<int Function(ffi.Pointer<psr_element_t1>)>();

  int psr_element_has_arrays(
    ffi.Pointer<psr_element_t1> element,
  ) {
    return _psr_element_has_arrays(
      element,
    );
  }

  late final _psr_element_has_arraysPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<psr_element_t1>)>>('psr_element_has_arrays');
  late final _psr_element_has_arrays =
      _psr_element_has_arraysPtr.asFunction<int Function(ffi.Pointer<psr_element_t1>)>();

  int psr_element_scalar_count(
    ffi.Pointer<psr_element_t1> element,
  ) {
    return _psr_element_scalar_count(
      element,
    );
  }

  late final _psr_element_scalar_countPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function(ffi.Pointer<psr_element_t1>)>>('psr_element_scalar_count');
  late final _psr_element_scalar_count =
      _psr_element_scalar_countPtr.asFunction<int Function(ffi.Pointer<psr_element_t1>)>();

  int psr_element_array_count(
    ffi.Pointer<psr_element_t1> element,
  ) {
    return _psr_element_array_count(
      element,
    );
  }

  late final _psr_element_array_countPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function(ffi.Pointer<psr_element_t1>)>>('psr_element_array_count');
  late final _psr_element_array_count =
      _psr_element_array_countPtr.asFunction<int Function(ffi.Pointer<psr_element_t1>)>();

  ffi.Pointer<ffi.Char> psr_element_to_string(
    ffi.Pointer<psr_element_t1> element,
  ) {
    return _psr_element_to_string(
      element,
    );
  }

  late final _psr_element_to_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<psr_element_t1>)>>('psr_element_to_string');
  late final _psr_element_to_string =
      _psr_element_to_stringPtr.asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<psr_element_t1>)>();

  void psr_string_free(
    ffi.Pointer<ffi.Char> str,
  ) {
    return _psr_string_free(
      str,
    );
  }

  late final _psr_string_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>('psr_string_free');
  late final _psr_string_free = _psr_string_freePtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<psr_lua_runner_t> psr_lua_runner_new(
    ffi.Pointer<psr_database_t> db,
  ) {
    return _psr_lua_runner_new(
      db,
    );
  }

  late final _psr_lua_runner_newPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<psr_lua_runner_t> Function(ffi.Pointer<psr_database_t>)>>(
          'psr_lua_runner_new');
  late final _psr_lua_runner_new =
      _psr_lua_runner_newPtr.asFunction<ffi.Pointer<psr_lua_runner_t> Function(ffi.Pointer<psr_database_t>)>();

  void psr_lua_runner_free(
    ffi.Pointer<psr_lua_runner_t> runner,
  ) {
    return _psr_lua_runner_free(
      runner,
    );
  }

  late final _psr_lua_runner_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<psr_lua_runner_t>)>>('psr_lua_runner_free');
  late final _psr_lua_runner_free = _psr_lua_runner_freePtr.asFunction<void Function(ffi.Pointer<psr_lua_runner_t>)>();

  int psr_lua_runner_run(
    ffi.Pointer<psr_lua_runner_t> runner,
    ffi.Pointer<ffi.Char> script,
  ) {
    return _psr_lua_runner_run(
      runner,
      script,
    );
  }

  late final _psr_lua_runner_runPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<psr_lua_runner_t>, ffi.Pointer<ffi.Char>)>>(
          'psr_lua_runner_run');
  late final _psr_lua_runner_run =
      _psr_lua_runner_runPtr.asFunction<int Function(ffi.Pointer<psr_lua_runner_t>, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> psr_lua_runner_get_error(
    ffi.Pointer<psr_lua_runner_t> runner,
  ) {
    return _psr_lua_runner_get_error(
      runner,
    );
  }

  late final _psr_lua_runner_get_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<psr_lua_runner_t>)>>(
          'psr_lua_runner_get_error');
  late final _psr_lua_runner_get_error =
      _psr_lua_runner_get_errorPtr.asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<psr_lua_runner_t>)>();
}

abstract class margaux_error_t {
  static const int MARGAUX_OK = 0;
  static const int MARGAUX_ERROR_INVALID_ARGUMENT = -1;
  static const int MARGAUX_ERROR_DATABASE = -2;
  static const int MARGAUX_ERROR_MIGRATION = -3;
  static const int MARGAUX_ERROR_SCHEMA = -4;
  static const int MARGAUX_ERROR_CREATE_ELEMENT = -5;
  static const int MARGAUX_ERROR_NOT_FOUND = -6;
}

abstract class psr_log_level_t {
  static const int PSR_LOG_DEBUG = 0;
  static const int PSR_LOG_INFO = 1;
  static const int PSR_LOG_WARN = 2;
  static const int PSR_LOG_ERROR = 3;
  static const int PSR_LOG_OFF = 4;
}

final class psr_database_options_t extends ffi.Struct {
  @ffi.Int()
  external int read_only;

  @ffi.Int32()
  external int console_level;
}

abstract class psr_data_structure_t {
  static const int PSR_DATA_STRUCTURE_SCALAR = 0;
  static const int PSR_DATA_STRUCTURE_VECTOR = 1;
  static const int PSR_DATA_STRUCTURE_SET = 2;
}

abstract class psr_data_type_t {
  static const int PSR_DATA_TYPE_INTEGER = 0;
  static const int PSR_DATA_TYPE_FLOAT = 1;
  static const int PSR_DATA_TYPE_STRING = 2;
}

final class psr_database extends ffi.Opaque {}

typedef psr_database_t = psr_database;

final class psr_element extends ffi.Opaque {}

typedef psr_element_t = psr_element;
typedef psr_element_t1 = psr_element;

final class psr_lua_runner extends ffi.Opaque {}

typedef psr_lua_runner_t = psr_lua_runner;
