// ignore_for_file: camel_case_types, non_constant_identifier_names
// Auto-generated by ffigen. Do not edit.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// FFI bindings for PSR Database C API
class PsrDatabaseBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  PsrDatabaseBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  PsrDatabaseBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  ffi.Pointer<ffi.Char> psr_error_string(
    int error,
  ) {
    return _psr_error_string(
      error,
    );
  }

  late final _psr_error_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int32)>>(
          'psr_error_string');
  late final _psr_error_string =
      _psr_error_stringPtr.asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  ffi.Pointer<ffi.Char> psr_version() {
    return _psr_version();
  }

  late final _psr_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'psr_version');
  late final _psr_version =
      _psr_versionPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  psr_database_options_t psr_database_options_default() {
    return _psr_database_options_default();
  }

  late final _psr_database_options_defaultPtr =
      _lookup<ffi.NativeFunction<psr_database_options_t Function()>>(
          'psr_database_options_default');
  late final _psr_database_options_default = _psr_database_options_defaultPtr
      .asFunction<psr_database_options_t Function()>();

  ffi.Pointer<psr_database_t> psr_database_open(
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<psr_database_options_t> options,
  ) {
    return _psr_database_open(
      path,
      options,
    );
  }

  late final _psr_database_openPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<psr_database_t> Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<psr_database_options_t>)>>('psr_database_open');
  late final _psr_database_open = _psr_database_openPtr.asFunction<
      ffi.Pointer<psr_database_t> Function(
          ffi.Pointer<ffi.Char>, ffi.Pointer<psr_database_options_t>)>();

  ffi.Pointer<psr_database_t> psr_database_from_migrations(
    ffi.Pointer<ffi.Char> db_path,
    ffi.Pointer<ffi.Char> migrations_path,
    ffi.Pointer<psr_database_options_t> options,
  ) {
    return _psr_database_from_migrations(
      db_path,
      migrations_path,
      options,
    );
  }

  late final _psr_database_from_migrationsPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<psr_database_t> Function(ffi.Pointer<ffi.Char>,
                  ffi.Pointer<ffi.Char>, ffi.Pointer<psr_database_options_t>)>>(
      'psr_database_from_migrations');
  late final _psr_database_from_migrations =
      _psr_database_from_migrationsPtr.asFunction<
          ffi.Pointer<psr_database_t> Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Pointer<psr_database_options_t>)>();

  ffi.Pointer<psr_database_t> psr_database_from_schema(
    ffi.Pointer<ffi.Char> db_path,
    ffi.Pointer<ffi.Char> schema_path,
    ffi.Pointer<psr_database_options_t> options,
  ) {
    return _psr_database_from_schema(
      db_path,
      schema_path,
      options,
    );
  }

  late final _psr_database_from_schemaPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<psr_database_t> Function(ffi.Pointer<ffi.Char>,
                  ffi.Pointer<ffi.Char>, ffi.Pointer<psr_database_options_t>)>>(
      'psr_database_from_schema');
  late final _psr_database_from_schema =
      _psr_database_from_schemaPtr.asFunction<
          ffi.Pointer<psr_database_t> Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Pointer<psr_database_options_t>)>();

  void psr_database_close(
    ffi.Pointer<psr_database_t> db,
  ) {
    return _psr_database_close(
      db,
    );
  }

  late final _psr_database_closePtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<psr_database_t>)>>(
      'psr_database_close');
  late final _psr_database_close = _psr_database_closePtr
      .asFunction<void Function(ffi.Pointer<psr_database_t>)>();

  int psr_database_is_healthy(
    ffi.Pointer<psr_database_t> db,
  ) {
    return _psr_database_is_healthy(
      db,
    );
  }

  late final _psr_database_is_healthyPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<psr_database_t>)>>(
      'psr_database_is_healthy');
  late final _psr_database_is_healthy = _psr_database_is_healthyPtr
      .asFunction<int Function(ffi.Pointer<psr_database_t>)>();

  ffi.Pointer<ffi.Char> psr_database_path(
    ffi.Pointer<psr_database_t> db,
  ) {
    return _psr_database_path(
      db,
    );
  }

  late final _psr_database_pathPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<psr_database_t>)>>('psr_database_path');
  late final _psr_database_path = _psr_database_pathPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<psr_database_t>)>();

  int psr_database_current_version(
    ffi.Pointer<psr_database_t> db,
  ) {
    return _psr_database_current_version(
      db,
    );
  }

  late final _psr_database_current_versionPtr = _lookup<
          ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<psr_database_t>)>>(
      'psr_database_current_version');
  late final _psr_database_current_version = _psr_database_current_versionPtr
      .asFunction<int Function(ffi.Pointer<psr_database_t>)>();

  int psr_database_set_version(
    ffi.Pointer<psr_database_t> db,
    int version,
  ) {
    return _psr_database_set_version(
      db,
      version,
    );
  }

  late final _psr_database_set_versionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>,
              ffi.Int64)>>('psr_database_set_version');
  late final _psr_database_set_version = _psr_database_set_versionPtr
      .asFunction<int Function(ffi.Pointer<psr_database_t>, int)>();

  int psr_database_migrate_up(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> migrations_path,
  ) {
    return _psr_database_migrate_up(
      db,
      migrations_path,
    );
  }

  late final _psr_database_migrate_upPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_database_t>,
              ffi.Pointer<ffi.Char>)>>('psr_database_migrate_up');
  late final _psr_database_migrate_up = _psr_database_migrate_upPtr.asFunction<
      int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>)>();

  int psr_database_begin_transaction(
    ffi.Pointer<psr_database_t> db,
  ) {
    return _psr_database_begin_transaction(
      db,
    );
  }

  late final _psr_database_begin_transactionPtr = _lookup<
          ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<psr_database_t>)>>(
      'psr_database_begin_transaction');
  late final _psr_database_begin_transaction =
      _psr_database_begin_transactionPtr
          .asFunction<int Function(ffi.Pointer<psr_database_t>)>();

  int psr_database_commit(
    ffi.Pointer<psr_database_t> db,
  ) {
    return _psr_database_commit(
      db,
    );
  }

  late final _psr_database_commitPtr = _lookup<
          ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<psr_database_t>)>>(
      'psr_database_commit');
  late final _psr_database_commit = _psr_database_commitPtr
      .asFunction<int Function(ffi.Pointer<psr_database_t>)>();

  int psr_database_rollback(
    ffi.Pointer<psr_database_t> db,
  ) {
    return _psr_database_rollback(
      db,
    );
  }

  late final _psr_database_rollbackPtr = _lookup<
          ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<psr_database_t>)>>(
      'psr_database_rollback');
  late final _psr_database_rollback = _psr_database_rollbackPtr
      .asFunction<int Function(ffi.Pointer<psr_database_t>)>();

  int psr_database_create_element(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<psr_element_t> element,
  ) {
    return _psr_database_create_element(
      db,
      collection,
      element,
    );
  }

  late final _psr_database_create_elementPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<psr_element_t>)>>('psr_database_create_element');
  late final _psr_database_create_element =
      _psr_database_create_elementPtr.asFunction<
          int Function(ffi.Pointer<psr_database_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<psr_element_t>)>();

  int psr_database_read_scalar_ints(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    ffi.Pointer<ffi.Pointer<ffi.Int64>> out_values,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_scalar_ints(
      db,
      collection,
      attribute,
      out_values,
      out_count,
    );
  }

  late final _psr_database_read_scalar_intsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<psr_database_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Int64>>,
              ffi.Pointer<ffi.Size>)>>('psr_database_read_scalar_ints');
  late final _psr_database_read_scalar_ints =
      _psr_database_read_scalar_intsPtr.asFunction<
          int Function(
              ffi.Pointer<psr_database_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Int64>>,
              ffi.Pointer<ffi.Size>)>();

  int psr_database_read_scalar_doubles(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    ffi.Pointer<ffi.Pointer<ffi.Double>> out_values,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_scalar_doubles(
      db,
      collection,
      attribute,
      out_values,
      out_count,
    );
  }

  late final _psr_database_read_scalar_doublesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<psr_database_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Double>>,
              ffi.Pointer<ffi.Size>)>>('psr_database_read_scalar_doubles');
  late final _psr_database_read_scalar_doubles =
      _psr_database_read_scalar_doublesPtr.asFunction<
          int Function(
              ffi.Pointer<psr_database_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Double>>,
              ffi.Pointer<ffi.Size>)>();

  int psr_database_read_scalar_strings(
    ffi.Pointer<psr_database_t> db,
    ffi.Pointer<ffi.Char> collection,
    ffi.Pointer<ffi.Char> attribute,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>> out_values,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _psr_database_read_scalar_strings(
      db,
      collection,
      attribute,
      out_values,
      out_count,
    );
  }

  late final _psr_database_read_scalar_stringsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<psr_database_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>,
              ffi.Pointer<ffi.Size>)>>('psr_database_read_scalar_strings');
  late final _psr_database_read_scalar_strings =
      _psr_database_read_scalar_stringsPtr.asFunction<
          int Function(
              ffi.Pointer<psr_database_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>,
              ffi.Pointer<ffi.Size>)>();

  void psr_free_int_array(
    ffi.Pointer<ffi.Int64> values,
  ) {
    return _psr_free_int_array(
      values,
    );
  }

  late final _psr_free_int_arrayPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Int64>)>>(
          'psr_free_int_array');
  late final _psr_free_int_array = _psr_free_int_arrayPtr
      .asFunction<void Function(ffi.Pointer<ffi.Int64>)>();

  void psr_free_double_array(
    ffi.Pointer<ffi.Double> values,
  ) {
    return _psr_free_double_array(
      values,
    );
  }

  late final _psr_free_double_arrayPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Double>)>>(
          'psr_free_double_array');
  late final _psr_free_double_array = _psr_free_double_arrayPtr
      .asFunction<void Function(ffi.Pointer<ffi.Double>)>();

  void psr_free_string_array(
    ffi.Pointer<ffi.Pointer<ffi.Char>> values,
    int count,
  ) {
    return _psr_free_string_array(
      values,
      count,
    );
  }

  late final _psr_free_string_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Size)>>('psr_free_string_array');
  late final _psr_free_string_array = _psr_free_string_arrayPtr
      .asFunction<void Function(ffi.Pointer<ffi.Pointer<ffi.Char>>, int)>();

  ffi.Pointer<psr_element_t1> psr_element_create() {
    return _psr_element_create();
  }

  late final _psr_element_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<psr_element_t1> Function()>>(
          'psr_element_create');
  late final _psr_element_create = _psr_element_createPtr
      .asFunction<ffi.Pointer<psr_element_t1> Function()>();

  void psr_element_destroy(
    ffi.Pointer<psr_element_t1> element,
  ) {
    return _psr_element_destroy(
      element,
    );
  }

  late final _psr_element_destroyPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<psr_element_t1>)>>(
      'psr_element_destroy');
  late final _psr_element_destroy = _psr_element_destroyPtr
      .asFunction<void Function(ffi.Pointer<psr_element_t1>)>();

  void psr_element_clear(
    ffi.Pointer<psr_element_t1> element,
  ) {
    return _psr_element_clear(
      element,
    );
  }

  late final _psr_element_clearPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<psr_element_t1>)>>(
      'psr_element_clear');
  late final _psr_element_clear = _psr_element_clearPtr
      .asFunction<void Function(ffi.Pointer<psr_element_t1>)>();

  int psr_element_set_int(
    ffi.Pointer<psr_element_t1> element,
    ffi.Pointer<ffi.Char> name,
    int value,
  ) {
    return _psr_element_set_int(
      element,
      name,
      value,
    );
  }

  late final _psr_element_set_intPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>,
              ffi.Int64)>>('psr_element_set_int');
  late final _psr_element_set_int = _psr_element_set_intPtr.asFunction<
      int Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>, int)>();

  int psr_element_set_double(
    ffi.Pointer<psr_element_t1> element,
    ffi.Pointer<ffi.Char> name,
    double value,
  ) {
    return _psr_element_set_double(
      element,
      name,
      value,
    );
  }

  late final _psr_element_set_doublePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>,
              ffi.Double)>>('psr_element_set_double');
  late final _psr_element_set_double = _psr_element_set_doublePtr.asFunction<
      int Function(
          ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>, double)>();

  int psr_element_set_string(
    ffi.Pointer<psr_element_t1> element,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _psr_element_set_string(
      element,
      name,
      value,
    );
  }

  late final _psr_element_set_stringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('psr_element_set_string');
  late final _psr_element_set_string = _psr_element_set_stringPtr.asFunction<
      int Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  int psr_element_set_null(
    ffi.Pointer<psr_element_t1> element,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _psr_element_set_null(
      element,
      name,
    );
  }

  late final _psr_element_set_nullPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_element_t1>,
              ffi.Pointer<ffi.Char>)>>('psr_element_set_null');
  late final _psr_element_set_null = _psr_element_set_nullPtr.asFunction<
      int Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>)>();

  int psr_element_set_array_int(
    ffi.Pointer<psr_element_t1> element,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Int64> values,
    int count,
  ) {
    return _psr_element_set_array_int(
      element,
      name,
      values,
      count,
    );
  }

  late final _psr_element_set_array_intPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Int64>, ffi.Int32)>>('psr_element_set_array_int');
  late final _psr_element_set_array_int =
      _psr_element_set_array_intPtr.asFunction<
          int Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Int64>, int)>();

  int psr_element_set_array_double(
    ffi.Pointer<psr_element_t1> element,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Double> values,
    int count,
  ) {
    return _psr_element_set_array_double(
      element,
      name,
      values,
      count,
    );
  }

  late final _psr_element_set_array_doublePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<psr_element_t1>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Double>,
              ffi.Int32)>>('psr_element_set_array_double');
  late final _psr_element_set_array_double =
      _psr_element_set_array_doublePtr.asFunction<
          int Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Double>, int)>();

  int psr_element_set_array_string(
    ffi.Pointer<psr_element_t1> element,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Pointer<ffi.Char>> values,
    int count,
  ) {
    return _psr_element_set_array_string(
      element,
      name,
      values,
      count,
    );
  }

  late final _psr_element_set_array_stringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<psr_element_t1>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Int32)>>('psr_element_set_array_string');
  late final _psr_element_set_array_string =
      _psr_element_set_array_stringPtr.asFunction<
          int Function(ffi.Pointer<psr_element_t1>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>, int)>();

  int psr_element_has_scalars(
    ffi.Pointer<psr_element_t1> element,
  ) {
    return _psr_element_has_scalars(
      element,
    );
  }

  late final _psr_element_has_scalarsPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<psr_element_t1>)>>(
      'psr_element_has_scalars');
  late final _psr_element_has_scalars = _psr_element_has_scalarsPtr
      .asFunction<int Function(ffi.Pointer<psr_element_t1>)>();

  int psr_element_has_arrays(
    ffi.Pointer<psr_element_t1> element,
  ) {
    return _psr_element_has_arrays(
      element,
    );
  }

  late final _psr_element_has_arraysPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<psr_element_t1>)>>(
      'psr_element_has_arrays');
  late final _psr_element_has_arrays = _psr_element_has_arraysPtr
      .asFunction<int Function(ffi.Pointer<psr_element_t1>)>();

  int psr_element_scalar_count(
    ffi.Pointer<psr_element_t1> element,
  ) {
    return _psr_element_scalar_count(
      element,
    );
  }

  late final _psr_element_scalar_countPtr = _lookup<
          ffi.NativeFunction<ffi.Size Function(ffi.Pointer<psr_element_t1>)>>(
      'psr_element_scalar_count');
  late final _psr_element_scalar_count = _psr_element_scalar_countPtr
      .asFunction<int Function(ffi.Pointer<psr_element_t1>)>();

  int psr_element_array_count(
    ffi.Pointer<psr_element_t1> element,
  ) {
    return _psr_element_array_count(
      element,
    );
  }

  late final _psr_element_array_countPtr = _lookup<
          ffi.NativeFunction<ffi.Size Function(ffi.Pointer<psr_element_t1>)>>(
      'psr_element_array_count');
  late final _psr_element_array_count = _psr_element_array_countPtr
      .asFunction<int Function(ffi.Pointer<psr_element_t1>)>();

  ffi.Pointer<ffi.Char> psr_element_to_string(
    ffi.Pointer<psr_element_t1> element,
  ) {
    return _psr_element_to_string(
      element,
    );
  }

  late final _psr_element_to_stringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<psr_element_t1>)>>('psr_element_to_string');
  late final _psr_element_to_string = _psr_element_to_stringPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<psr_element_t1>)>();

  void psr_string_free(
    ffi.Pointer<ffi.Char> str,
  ) {
    return _psr_string_free(
      str,
    );
  }

  late final _psr_string_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'psr_string_free');
  late final _psr_string_free =
      _psr_string_freePtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();
}

abstract class psr_error_t {
  static const int PSR_OK = 0;
  static const int PSR_ERROR_INVALID_ARGUMENT = -1;
  static const int PSR_ERROR_DATABASE = -2;
  static const int PSR_ERROR_MIGRATION = -3;
  static const int PSR_ERROR_SCHEMA = -4;
  static const int PSR_ERROR_CREATE_ELEMENT = -5;
  static const int PSR_ERROR_NOT_FOUND = -6;
}

abstract class psr_log_level_t {
  static const int PSR_LOG_DEBUG = 0;
  static const int PSR_LOG_INFO = 1;
  static const int PSR_LOG_WARN = 2;
  static const int PSR_LOG_ERROR = 3;
  static const int PSR_LOG_OFF = 4;
}

final class psr_database_options_t extends ffi.Struct {
  @ffi.Int()
  external int read_only;

  @ffi.Int32()
  external int console_level;
}

final class psr_database extends ffi.Opaque {}

typedef psr_database_t = psr_database;

final class psr_element extends ffi.Opaque {}

typedef psr_element_t = psr_element;
typedef psr_element_t1 = psr_element;
