# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/bindings/python"
    schedule:
      interval: "monthly"

  - package-ecosystem: "julia"
    directory: "/bindings/julia"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "/bindings/dart"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/bindings/js"
    schedule:
      interval: "monthly"
